### ISSUE TITLE
Tests reporting success when they've actually failed.

### ISSUE THREAD

**Issue by ghost** [square/zapp#27]
One of our KIF scenarios, somewhere in the middle of our test suite, is failing. Zapp then seems to be noticing this, and decides to run the tests again, starting from the next scenario after the failing one. This remaining set of scenarios all passes, and it seems like Zapp then hence decides that this means the whole build was a success. This doesn't seem right :-)

I'm not quite sure why Zapp is doing this business of stopping and continuing the tests if one fails, but I'm sure there's a good reason for it. However, I think that the reason this bug is happening lies in line 385 of ZappBuild.m:

``` objc
[self runSimulatorWithAppPath:appPath initialSkip:lastStartedScenario - 1 failureCount:newFailureCount - 1 startsWithRetry:YES];
```

I've got a feeling that you shouldn't be subtracting one from newFailureCount? In our example, this means that failureCount in the recursive call is 0, when I believe it should be 1.

**Comment by puls** [comment]
Can you provide any more information about what's going on? Notice that Zapp retries a failing scenario after relaunching the app once, so we subtract one here from both the initial skip and the failure count. Three lines earlier, in the case where the scenario fails again, we pass the unaltered newFailureCount on.

**Comment by ghost** [comment]
Yep - I'll try to reproduce, and add a bit of debugging output.

**Comment by ghost** [comment]
I finally got round to looking into this - I made a test app and am unable to reproduce, so I'm going to close this issue unless I come across it again, instead of wasting your time :-) I was however wondering what the motivation is for making Zapp retry a failing scenario?
