### ISSUE TITLE
Build Issue?

### ISSUE THREAD

**Issue by heavyC** [square/zapp#32]
I am getting
Mac68k alignment pragma is not supported on this target
in the MacTypes.h file for the line:
# pragma options align=mac68k

This is from the unaltered download project in Xcode 4.2.  Can't figure out what the problem is.

**Comment by puls** [comment]
Neither can we, unless you provide more information. What's the full build output?

**Comment by heavyC** [comment]
This is the complete build output.  CoreFoundation.framework is correctly in the build, and there are no errors surrounding frameworks.

Zapp Group
/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator3.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h
/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator3.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:84:10: fatal error: 'CoreFoundation/CFUserNotification.h' file not found [2]

/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator3.2.sdk/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/Headers/MacTypes.h
/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator3.2.sdk/System/Library/Frameworks/CoreServices.framework/Headers/../Frameworks/CarbonCore.framework/Headers/MacTypes.h:36:9: error: mac68k alignment pragma is not supported on this target [3]

Build task failed without generating error messages.

**Comment by puls** [comment]
Not sure how you're compiling for the iPhone Simulator platform. This is a Mac app.

**Comment by heavyC** [comment]
Needed Lion OS.  yo estoy n00b.
Sorry for troubles.
